### PR TITLE
Adds a Tool for using the Transfer MkDir Action Provider

### PR DESCRIPTION
**Pull request by jimPruyne**
This implements a slightly different, but intending to be compatible, version of some elements of a tool. Notably:

- Properties for the state can be set on the `__init__` method of the tool class. This leads to a model where tools tend to be included in clients based on instances rather than Class objects or class name strings. However, because all arguments to `__init__` have default values, and those defaults are using the pattern of other tools, it should behave as other Tools when used based on Class object or name.

- The `flow_definition` is dynamically generated based on parameters to the `__init__`. This allows some of the things often set by `modifiers` to be set by the values in `__init__`.

- Likewise, the `required_input` is dynamically generated and can adapt to different values placed in the `__init__`.

### CODE REVIEW

**Comment by jimPruyne** [comment]
I see some github Action failures, but I think that may be unrelated to this PR. That begs the question of tests for this new code. I don't see tests for the `Transfer` tool which would seem to be the model for this. Should I look into a test, and, if so, would there be a `Transfer` one I'm not seeing to use as a tempalte?

**Comment by NickolausDS** [comment]
Yeah, don't worry about the tests. Publishv2 has some problems.

This newer approach to tools is an interesting one. I really like the ability to change properties of the flow by passing init parameters, although that does also break some existing properties of Gladier tools, such as Aliases. 

Additionally, it feels like the Action State parameters are a little cumbersome here. If it's up to the developer to decide whether WaitTime is supported, it may be difficult for users to assume behavior on different tools. This seems like a good place for method chaining based on the category of changes a user would want to apply on a tool. Maybe one method for top level state attributes, and another one specific to the tool. For example:

```
GlobusMkDir().set_state(wait_time=600, result_path="$.MyMkdir").set_input(endpoint_id="$.input.my_ep_id")
```

Above, `.set_state()` would contain a set list of parameters that never changes. `.set_input()` on the other hand would be overrided by the developer to provide specific access to changing attributes of the specific flow in question.

**Comment by jimPruyne** [comment]
Thanks for the feedback.

I've never fully understood what the role of the alias is, so if this is breaking or inconsistent with that, I'm not at all surprised. Perhaps we can talk more about that though I do admit that one iteration of this was failing because `self.alias` was not set (and the call to the super init solved that).

I'm not too clear on:
> If it's up to the developer to decide whether WaitTime is supported, it may be difficult for users to assume behavior on different tools.

Are you saying that developers may create different tools where some support WaitTime (as an example) and some do not?

I would have two thoughts on that:

1. Really, any Tool class that represents a (single) Action state in a flow should inherit from a common Action tool base class and that's where the Action state specific things (like wait time or result path) would be handled. That _does_ make generation of the flow for the tool more complicated as parts of the generated flow state would come from the parent class and parts from the tool class. I'm not sure I have a solution to that immediately.
2. I'm leaning into tooling and so on where by putting the parameters in the init, a developer *using* the tool sees immediately what things can be set and so would see stuff like the wait_time parameter at that point.

I see where the chaining can work though it seems one would then have to do something like:
```python
class AGladierClient(GladierClient):
    tools = [GladierMkDir().set_state(...).set_input(...)]
```
which reads a bit cumbersome to me.

But, I think main thing is you're likely see aspects of when or how different values are set compared to when flows are generated and input is passed during run-time that I'm perhaps missing.

Do you want to keep moving forward on this conversation? Do you want to drop this PR entirely? Do you want a `GlobusMkDir` tool that behaves more like other tools (e.g. the Transfer tool)?

**Comment by NickolausDS** [comment]
> Do you want to keep moving forward on this conversation?

I absolutely want to continue this conversation. This could serve as a potential alternative for modifiers and aliases, both of which have problems and I've noticed others have had issues using. If we both can agree on a model that we think works better than both of those, I'd like to consider switching to it.

> Do you want to drop this PR entirely? Do you want a GlobusMkDir tool that behaves more like other tools (e.g. the Transfer tool)?

Until we're solid on what future tools should look like, I'd prefer to keep the old style of tools. That said, if you have a burning desire to use this in more than one project, we could start an `experimental` location for new tools that looks something like this: `gladier_tools.experimental.posix.MkDir`.

On the subject of adding parameters to `__init__()`, let's talk about that more! We can do that in a different venue if you want. Mainly I'm thinking of ways of separating parameters that never change (state params like action_url, wait_time) with parameters that are likely to change (any custom tool specific params, probably within Parameters). Plus, there is currently legacy stuff on __init__() we'd have to think about for Gladier Base Tools.

**Comment by jimPruyne** [comment]
Sorry this slipped of my radar a bit earlier this week.

I'm good with the experimental sub-package to try some things out and then we can see if/how we migrate that to other parts of the Gladier codebase.

So, I'm modifying this PR to put it in an experimental sub-tree and fleshing out some base classes etc that might support this model more cleanly.

**Comment by jimPruyne** [comment]
@NickolausDS I think this has calmed down to the point that it is worth taking a look at. There still seems to be some tweaking that could be done to clean things up, but overall I think it captures the general approach here. Let me know if you'd like to chat about this. I think the next step would be to add support for ~funcX~ Globus Compute.

**Review by NickolausDS — APPROVED** [review]
Looks good! Thanks Jim!

In case anyone else is reading this, the changes here are VERY experimental and I think we've already discussed some breaking changes we want to add to these classes. High level items include:

* Separating Gladier "Tool" definitions from State Level definitions, and considering a State level API for Gladier
* Expanding the way states can be appended onto Tools, such that a tool could be composed out of smaller State classes
* Defining options for chaining classes together to match conventions present in the AWS CDK.

**Pull request merged**
